version: '3.4'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: nest
      MYSQL_ROOT_PASSWORD: mysqlpassword
    ports:
      - 3306:3306
    networks:
      - nestjs-typeorm

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - nestjs-typeorm

networks:
  nestjs-typeorm:
